[project]
name = "cdm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ale-py < 0.10.1",
    "gymnasium < 1.0.0",
    "matplotlib>=3.9.2",
    "pygame>=2.6.1",
]
